spring:
  application:
    name: fault-collector

server:
  port: 8080

processor:
  base-url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
